version: "3.8"

# services:
#   data-visualization-app:
#     build: .
#     container_name: data-visualization-app
#     restart: always
#     ports:
#       - "8010:8050"
#     environment:
#       - PYTHONUNBUFFERED=1

services:
  data-visualization-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BUST: "2025-11-19-2"
    container_name: data-visualization-app
    restart: always
    ports:
      - "8010:8050"
    environment:
      - PYTHONUNBUFFERED=1